## Q1. Create a Random Tensor with Shape (7,7).

In [1]:
import torch

In [2]:
tensor1 = torch.rand(size=(7,7))
tensor1,tensor1.shape

(tensor([[0.8274, 0.5708, 0.5912, 0.2658, 0.5473, 0.5693, 0.5636],
         [0.2086, 0.1145, 0.8089, 0.1493, 0.6265, 0.4624, 0.3313],
         [0.3604, 0.3015, 0.3420, 0.3939, 0.1413, 0.2017, 0.4463],
         [0.4560, 0.2287, 0.7860, 0.5355, 0.9276, 0.3370, 0.2292],
         [0.8139, 0.4003, 0.9577, 0.0497, 0.5832, 0.0805, 0.8507],
         [0.5604, 0.0734, 0.3259, 0.8819, 0.0267, 0.5194, 0.3942],
         [0.0278, 0.7676, 0.0860, 0.3112, 0.1926, 0.1613, 0.2776]]),
 torch.Size([7, 7]))

## Q2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1,7).

In [3]:
tensor2 = torch.rand(size=(1,7))
tensor3 = torch.mm(tensor1,tensor2.T)
tensor3,tensor3.shape

(tensor([[1.4309],
         [0.7453],
         [0.7673],
         [0.8835],
         [1.0189],
         [0.9274],
         [0.9602]]),
 torch.Size([7, 1]))

## Q3. Set the Random seed to 0 and do 2 & 3 over again.

In [4]:
torch.manual_seed(0)
tensor1 = torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))

tensor3 = torch.mm(tensor1,tensor2.T)
tensor3,tensor3.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

## Q4. Create two random tensors of shape (2,3) and send them both to the GPU.

In [5]:
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"The device is: {device}")
first_tensor = torch.rand(size=(2,3)).to(device)
second_tensor = torch.rand(size=(2,3)).to(device)
first_tensor,second_tensor

The device is: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

## Q5. Perform a multiplication in the tensors you created in Q4 above. 

In [6]:
third_tensor = torch.mm(first_tensor,second_tensor.T)
third_tensor,third_tensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

## Q6. Find the Maximum and Minimum values of the output of Q5.

In [7]:
maximum_value = torch.argmax(third_tensor)
maximum_value

tensor(3)

In [8]:
minimum_value = torch.argmin(third_tensor)
minimum_value

tensor(0)

## Q7. Make a random tensor with shape (1,1,1,10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).

In [10]:
torch.manual_seed(7)
fourth_tensor = torch.rand(1,1,1,10)
# Remove a single dimension
fifth_tensor = fourth_tensor.squeeze()

print(fourth_tensor,fourth_tensor.shape)
print(fifth_tensor,fifth_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
